export const CHANNELS_LOAD = 'CHANNELS_LOAD';
export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_SELECT = 'CHANNEL_SELECT';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_RENAME = 'CHANNEL_RENAME';
export const CHANNEL_ORDER_UP = 'CHANNEL_ORDER_UP';
export const CHANNEL_ORDER_DOWN = 'CHANNEL_ORDER_DOWN';

export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_UPVOTE = 'MESSAGE_UPVOTE';
export const MESSAGE_DOWNVOTE = 'MESSAGE_DOWNVOTE';

export const USER_LOGIN = 'USER_LOGIN';
