export const CHANNEL_CREATE = 'CHANNEL_CREATE';
export const CHANNEL_SELECT = 'CHANNEL_SELECT';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_RENAME = 'CHANNEL_RENAME';
export const MESSAGE_SEND = 'MESSAGE_SEND';
